linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - misspell
    - gocyclo
    - gosec
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

run:
  deadline: 5m
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true
