version: '3.8'

services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        ALPHA_VANTAGE_API_KEY: ${ALPHA_VANTAGE_API_KEY}
        DATA_SOURCE_NAME: ${DATA_SOURCE_NAME}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - internal_network

volumes:
  postgres_data:

networks:
  internal_network:
    driver: bridge
