services:
  db:
    container_name: finscope-store
    image: postgres:17
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_network

  api:
    container_name: finscope-api-server
    build:
      target: dev
      args:
        CONFIG_PATH: ${CONFIG_PATH}
        DATA_SOURCE_NAME: ${DATA_SOURCE_NAME}
        LOG_LEVEL: ${LOG_LEVEL}
        AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
        HMAC_SECRET: ${HMAC_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - internal_network

volumes:
  postgres_data:

networks:
  internal_network:
    driver: bridge
