services:
  db:
    container_name: financial-data-db
    image: postgres:17
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_network

  api:
    container_name: financial-data-api-server
    build:
      context: ../
      dockerfile: ./dev-setup/api/Dockerfile
      target: dev
      args:
        ALPHA_VANTAGE_API_KEY: ${ALPHA_VANTAGE_API_KEY}
        DATA_SOURCE_NAME: ${DATA_SOURCE_NAME}
        LOG_LEVEL: ${LOG_LEVEL}
        ALGORITHM_FILE_NAME: ${ALGORITHM_FILE_NAME}
        AUTH0_DOMAIN: ${AUTH0_DOMAIN}
        AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
        AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
        AUTH0_CALLBACK_URL: ${AUTH0_CALLBACK_URL}
        HMAC_SECRET: ${HMAC_SECRET}
        AUTH0_API_AUDIENCE: ${AUTH0_API_AUDIENCE}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - internal_network

volumes:
  postgres_data:

networks:
  internal_network:
    driver: bridge
